#!/usr/bin/python

#
# Copyright 2014 Armin Briegel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A tool that helps manage and manipulate `autopkg` recipes."""

import os, subprocess

import argparse
from argparse import RawTextHelpFormatter

recipeutil_version = '0.1'
args=[]

def logger(log, v=0):
    if args.verbosity >= v:
        print log;

def cmdexec(command):
    """Execute a command."""

    # if 'command' is a string, split the string into components
    if isinstance(command, str):
        command = command.split()

    proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (stdout, stderr) = proc.communicate()

    logger("cmdexec: %s, result: %s, error: %s" % (command, stdout, stderr), 3)

    # strip trailing whitespace, which would mess with string comparisons
    return {"return_code": proc.returncode, "stderr": stderr.rstrip(), "stdout": stdout.rstrip()}

def get_recipe_data(recipe_name_or_id):
    cmd_result = cmdexec(["autopkg", "info", recipe_name_or_id])
    if (cmd_result['return_code'] == 0):
        recipe_data = {"full_info":cmd_result['stdout']}
        for l in cmd_result['stdout'].splitlines():
            if l.startswith("Identifier:"):
                recipe_data['identifier'] = l[21:]
            if l.startswith("Recipe file path:"):
                recipe_data['path'] = l[21:]
            if l.startswith("Parent recipe(s):"):
                recipe_data['parent_path'] = l[21:]
        logger(recipe_data, 3)
        return recipe_data
    else:
        print "cannot read recipe %s! (return_code = %d)" % (recipe_name_or_id, cmd_result['return_code'])
        exit(1)



def recipe_info(recipe_data):
    print recipe_data["full_info"]

def recipe_which(recipe_data):
    print recipe_data["path"]

def recipe_id(recipe_data):
    print recipe_data["identifier"]

def recipe_open(recipe_data):
    path = recipe_data['path']
    cmdexec(['open', path])

def recipe_reveal(recipe_data):
    path = recipe_data['path']
    cmdexec(['open', '-R', path])

def recipe_edit(recipe_data):
    path = recipe_data['path']
    if 'RECIPE_EDITOR' in os.environ:
        editor = os.environ['RECIPE_EDITOR'].split()
    else:
        editor = os.environ['EDITOR'].split()
    editor.append(path)
    if len(args.extra_args) > 0:
        editor.extend(args.extra_args)
    logger("Editor: %s" % (editor), 2)
    cmdexec(editor)

def recipe_status(recipe_data):
    dir_path = os.path.dirname(recipe_data['path'])
    cmds = ['git', '-C', dir_path, 'status']
    if len(args.extra_args) > 0:
        cmds.extend(args.extra_args)
    logger(cmds, 2)
    result = cmdexec(cmds)
    print result['stdout']

if __name__ == "__main__":
    actions = { 
        'info':recipe_info, 
        'which': recipe_which, 
        'path': recipe_which, 
        'identifier':recipe_id , 
        'id':recipe_id, 
        'open':recipe_open,
        'reveal':recipe_reveal,
        'show': recipe_reveal,
        'edit': recipe_edit,
        'status': recipe_status
        }
    # step 0: parse input from cli

    # for convenience link to argparse tutorial:
    # https://docs.python.org/2/howto/argparse.html#id1
    parser = argparse.ArgumentParser(description='A tool that helps manage and manipulate `autopkg` recipes.', 
                    epilog="""actions can be one of the following:
    info                synonym for `autopkg info`
    which or path       prints the path to the recipe_id
    identifier or id    prints the identifier for the recipe
    open                opens recipe with default application for recipe files
    reveal or show      reveals the recipe file in the Finder
    edit                opens the recipe in the text editor set in $EDITOR
                        if $RECIPE_EDITOR is set it will be used instead
    status              runs 'git status' on the directory enclosing the recipe
    
    for 'status' and 'edit' additional options will be passed into the command
    e.g.: recipeutil status Firefox.download --short
    """, formatter_class=RawTextHelpFormatter)

    parser.add_argument('--version', help='prints the version', action='version', version=recipeutil_version)

    parser.add_argument('action', choices=sorted(actions.keys()), help='action to be applied to the recipe')

    parser.add_argument("-v", "--verbosity", action="count", default=0, help="controls amount of logging output (max -vvv)")
    parser.add_argument("-n", "--names", action="store_true", help="prints the recipes' names before the info.")

    parent_option_group = parser.add_mutually_exclusive_group()
    parent_option_group.add_argument('--parent', '-p', action='store_true', help="apply the action to parent of the recipe")
    parent_option_group.add_argument('--all-parents', '-a', action='store_true', help="apply the action to the recipe and all its parents")

    parser.add_argument('recipe_name_or_id', help="the recipe name or id")
    parser.add_argument('extra_args', nargs=argparse.REMAINDER, help="extra arguments will be passed through to 'edit' and 'status' commands")

    # finally, actually parse the arguments
    args = parser.parse_args()
    logger(args, 3)
    #args.func(args)

    # get the recipe data
    recipe_data = get_recipe_data(args.recipe_name_or_id)
    
    # if --parent is set, replace recipe_data with its parent
    if args.parent:
        if 'parent_path' in recipe_data:
            recipe_data = get_recipe_data(recipe_data['parent_path'])
        else:
            print "%s does not have a parent recipe!" % (args.recipe_name_or_id)
            exit(1)
    
    recipe_list = [recipe_data]
    
    # if --all-parents is set work through the list
    
    if args.all_parents:
        while 'parent_path' in recipe_data:
            recipe_data = get_recipe_data(recipe_data['parent_path'])
            recipe_list.append(recipe_data)
    
    # apply action to all items in recipe_data
    l = len(recipe_list)
    for r in recipe_list:
        if args.names:
            print
            print os.path.basename(r['path'])
        actions[args.action](r)


